### ISSUE TITLE
Retroalimentación sprint 1

### ISSUE THREAD

**Issue by FabianBravoA** [scarleette/scl-2018-05-bc-core-pm#1]
Se que hiciste la interfaz, pero es importante que avances en tu código para cifrar. De todas formas, a pesar de que está correcto el flujo que hiciste, trata de simplificarlo, cosa de que sea más fácil para ti manejar todo. Te recomiendo hacer todo en una misma página, es más simple y fácil de manejar.

**Comment by scarleette** [comment]
lo lei tarde , pero lo hice, gracias .
